### ISSUE TITLE
API Testing in Python Course

### ISSUE THREAD

**Issue by TsireledzoRavelle** [automationhacks/ama#6]
Hi, I am having this attribute error when I try to run build_database.py

/Users/tsireledzo.ravelle/.local/share/virtualenvs/people-api-FkAw6jw4/bin/Python /Users/tsireledzo.ravelle/people-api/build_database.py
Traceback (most recent call last):
  File "/Users/tsireledzo.ravelle/people-api/build_database.py", line 15, in <module>
    db.create_all()
  File "/Users/tsireledzo.ravelle/.local/share/virtualenvs/people-api-FkAw6jw4/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1039, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/Users/tsireledzo.ravelle/.local/share/virtualenvs/people-api-FkAw6jw4/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1031, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/Users/tsireledzo.ravelle/.local/share/virtualenvs/people-api-FkAw6jw4/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 962, in get_engine
    return connector.get_engine()
  File "/Users/tsireledzo.ravelle/.local/share/virtualenvs/people-api-FkAw6jw4/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 555, in get_engine
    options = self.get_options(sa_url, echo)
  File "/Users/tsireledzo.ravelle/.local/share/virtualenvs/people-api-FkAw6jw4/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 570, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/Users/tsireledzo.ravelle/.local/share/virtualenvs/people-api-FkAw6jw4/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 914, in apply_driver_hacks
    sa_url.database = os.path.join(app.root_path, sa_url.database)
AttributeError: can't set attribute

Process finished with exit code 1

**Comment by automationhacks** [comment]
Hi @TsireledzoRavelle , Are you still facing this issue. Please ask this question on the actual repo if still not resolved. https://github.com/automationhacks/course-api-framework-python
